# Generated by Django 4.2.3 on 2023-07-22 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cer_ser', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Musician',
            new_name='Certificates_Makers',
        ),
    ]
