# Generated by Django 4.2.3 on 2023-07-25 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cer_ser', '0002_rename_musician_certificates_makers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate_Owners',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate_Tokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checksum', models.CharField(max_length=50)),
                ('real_token', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='certificates',
            old_name='content_pos',
            new_name='image_url',
        ),
        migrations.RemoveField(
            model_name='certificates',
            name='date_pos',
        ),
        migrations.RemoveField(
            model_name='certificates',
            name='image_name',
        ),
        migrations.RemoveField(
            model_name='certificates',
            name='signature_pos',
        ),
        migrations.AddField(
            model_name='certificates',
            name='date_padding',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='certificates',
            name='date_pos_right',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='certificates',
            name='date_pos_top',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='certificates',
            name='signature_padding',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='certificates',
            name='signature_pos_right',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='certificates',
            name='signature_pos_top',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='certificates',
            name='text_padding',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='certificates',
            name='text_pos_right',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='certificates',
            name='text_pos_top',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.DeleteModel(
            name='Certificates_Makers',
        ),
        migrations.AddField(
            model_name='certificates',
            name='owner_email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cer_ser.certificate_owners'),
        ),
    ]
