# Generated by Django 4.2.3 on 2023-07-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cer_ser', '0004_rename_date_pos_right_certificates_date_pos_left_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='date_color',
            field=models.CharField(default='red', max_length=50),
        ),
        migrations.AddField(
            model_name='certificates',
            name='signature_color',
            field=models.CharField(default='red', max_length=50),
        ),
        migrations.AddField(
            model_name='certificates',
            name='text_color',
            field=models.CharField(default='red', max_length=50),
        ),
        migrations.AddField(
            model_name='certificates',
            name='token_color',
            field=models.CharField(default='red', max_length=50),
        ),
    ]
