# Generated by Django 4.2.3 on 2023-07-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cer_ser', '0005_certificates_date_color_certificates_signature_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='date_font_size',
            field=models.CharField(default='20', max_length=255),
        ),
        migrations.AddField(
            model_name='certificates',
            name='signature_font_size',
            field=models.CharField(default='20', max_length=255),
        ),
        migrations.AddField(
            model_name='certificates',
            name='text_font_size',
            field=models.CharField(default='20', max_length=255),
        ),
    ]
